### ISSUE TITLE
feature/advanced-msg-paramter ?

### ISSUE THREAD

**Issue by matepek** [hbenl/vscode-test-adapter-util#1]
would you mind something like this: `debug(msg: any[]): void` ?
I can make it if you think.
(using util.inspect)

**Comment by hbenl** [comment]
That sounds like a good idea, I'd accept a PR.

**Comment by matepek** [comment]
Is there any chance merging my pull request in the near future?

**Comment by hbenl** [comment]
Sorry for the delay, I've merged and published it now.
